config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :users
  namespace :site do
  get 'welcome/index'
  get 'search', to: 'search#questions'
  get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
  post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  devise_for :admins, skip: [:registrations]
  get 'inicio', to: 'site/welcome#index'
  get 'backoffice', to: 'admins_backoffice/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado!"
        else 
        render :edit
    end
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
    redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado!"
    else 
      render :new
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído!"
      else 
      render :index
    end
  end
    
  private

  def params_admin
    params_admin = params.require(:admin).permit(:email, :password, :password_confirmation)
  end
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def verify_password
    if params[:admin] [:password].blank? && params[:admin] [:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject)
                         .order(:description)
                         .page(params[:page])
  end

  def new
  @question = Question.new
  end
  
  def create
  @question = Question.new(params_question)
    if @question.save
    redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
      else
        render :new
    end
  end
  
  def edit
  end
  
  def update
    if @question.update(params_question)
    redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
      else
        render :edit
    end
  end
  
  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
        else
        render :index
    end
  end
  
  private
  def params_question
  params.require(:question).permit(:description, :subject_id,
                                  answers_attributes: [:id, :description, :correct, :_destroy])
  end
  
  def set_question
  @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end

  end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all.order(:description).page(params[:page]).per(15)
  end

  def edit
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado!"
        else 
      render :edit
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
    redirect_to admins_backoffice_subjects_path, notice: "Assunto cadastrado!"
    else 
      render :new
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído!"
      else 
      render :index
    end
  end
    
  private

  def params_subject
    params_subject = params.require(:subject).permit(:description)
  end
  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
             locals: { action_message: 'Editando'} %>

app/views/admins_backoffice/subjects/index.html.erb
  <div class="col-lg-12">
  <h1 class="page-header"><%= t('messages.listing', model: @subjects.model_name.human(count: 2)) %></h1>
  </div>
  <!-- /.col-lg-12 -->


<div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="dataTable_length">
<label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm">
<option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label>
</div></div><div class="col-sm-12 col-md-6"><div id="dataTable_filter" class="dataTables_filter">
<label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label>
</div></div></div>

<div class="row"><div class="col-sm-8">
<table id="dataTable" role="grid" aria-describedby="dataTable_info" style="width: 100%;" class="table table-bordered dataTable table-hover" width="100%" cellspacing="0">
    <thead>
        <tr role="row">
        <th rowspan="1" colspan="1"><%= translate_attribute(@subjects, :id) %></th>
        <th rowspan="1" colspan="1"><%= translate_attribute(@subjects, :description) %></th>
        <th rowspan="1" colspan="1">
          <%= link_to new_admins_backoffice_subject_path, class:"btn btn-success btn-circle" do %> 
          <i class="fa fa-plus"></i>
          <% end %>Cadastrar  
        </th>
    </thead>
    <tfoot>
        <tr>
        <th rowspan="1" colspan="1"><%= translate_attribute(@subjects, :id) %></th>
        <th rowspan="1" colspan="1"><%= translate_attribute(@subjects, :description) %></th>
        <th rowspan="1" colspan="1">Editar/Apagar</th>
        </tr>
    </tfoot>
    <tbody>
    <% @subjects.each do |subject| %>
    <tr class="odd">
    <td class="sorting_1"> <%= subject.id %> </td>
    <td> <%= subject.description %> </td>
    <td style="width: 170px"> 
    
    <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle" do %> 
      <i class="fa fa-edit"></i>
    <% end %>

    <%= link_to admins_backoffice_subject_path(subject), method: :delete, class:"btn btn-danger btn-circle" do %> 
      <i class="fa fa-minus"></i>
    <% end %>
  </td>
    </tr>
    <% end %>
    </tbody>
</table>


<%= paginate @subjects  %>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: { action_message: 'Nova'} %>